title: Gavin Yuan
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://memrtroll.github.io

#plugins:
 
aux_links:
  Template Repository: https://github.com/memrtroll/memrtroll.github.io
  Aux Link 2: http://google.com
aux_links_new_tab: false
