title: Gavin Yuan
description: Gavin's personal website.
theme: just-the-docs
color_scheme: gy
url: https://gavinbuilds.github.io
favicon_ico: "/assets/images/yep.png"
#plugins:

# Aux links for the upper right navigation
aux_links:
  Repo: https://github.com/gavinbuilds/gavinbuilds.github.io
  Notion Pages: http://google.com
aux_links_new_tab: true
opens_in_new_tab: true
nav_external_links_new_tab: true

#back_to_top: true
#back_to_top_text: "Back to top"

heading_anchors: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

footer_navigation:
  previous: Previous
  next: next

footer_external_links:
  - label: Contact
    url: docs\01-contact.md

