title: Gavin Yuan
description: Gavin's personal website using the Just the Docs theme!
theme: just-the-docs

url: https://memrtroll.github.io

#plugins:

# Aux links for the upper right navigation
aux_links:
  Template Repository: https://github.com/memrtroll/memrtroll.github.io
  Aux Link 2: http://google.com
aux_links_new_tab: false

back_to_top: true
back_to_top_text: "Back to top"

heading_anchors: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
